config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  get 'movies/filter/:filter' => 'movies#index', as: :filtered_movies

  resources :movies do
    resources :reviews
    resources :favorites, only: %i[create destroy]
  end

  resources :users
  get 'signup' => 'users#new'

  resources :sessions, only: %i[new create destroy]
  get 'signin' => 'sessions#new'

  resources :genres
end

app/models/movie.rb
class Movie < ApplicationRecord
  before_save :set_slug

  has_many :reviews, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user
  has_many :characterizations
  has_many :genres, through: :characterizations

  RATINGS = %w[G PG PG-13 R NC-17]

  validates :title, presence: true, uniqueness: true
  validates :released_on, :duration, presence: true
  validates :description, length: { minimum: 25 }
  validates :total_gross, numericality: { greater_than_or_equal_to: 0 }
  validates :image_file_name, format: {
    with: /\w+\.(jpg|png)\z/i,
    message: 'must be a JPG or PNG image'
  }
  validates :rating, inclusion: { in: RATINGS }

  scope :released, -> { where('released_on < ?', Time.now).order('released_on desc') }
  scope :upcoming, -> { where('released_on > ?', Time.now).order('released_on asc') }
  scope :recent, ->(max = 5) { released.limit(max) }
  scope :hits, -> { released.where('total_gross >= 300000000').order(total_gross: :desc) }
  scope :flops, -> { released.where('total_gross < 300000000').order(total_gross: :asc) }
  scope :grossed_less_than, ->(amount) { released.where('total_gross < ?', amount).order('total_gross desc') }
  scope :grossed_greater_than, ->(amount) { released.where('total_gross > ?', amount).order('total_gross asc') }

  def flop?
    return if reviews.count >= 50 && average_stars >= 4

    (total_gross.blank? || total_gross < 225_000_000)
  end

  def average_stars
    reviews.average(:stars) || 0.0
  end

  def average_stars_as_percent
    (average_stars / 5.0) * 100
  end

  def to_param
    slug
  end

  private

  def set_slug
    self.slug = "#{id}-#{title.parameterize}"
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_signin, except: %i[index show]
  before_action :require_admin, except: %i[index show]
  before_action :set_movie, only: %i[show edit update destroy]

  def index
    @movies = case params[:filter]
              when 'upcoming'
                Movie.upcoming
              when 'recent'
                Movie.recent
              when 'hits'
                Movie.hits
              when 'flops'
                Movie.flops
              else
                Movie.released
              end
  end

  def show
    @movie = Movie.find_by!(slug: params[:id])
    @review = @movie.reviews.new
    @fans = @movie.fans
    @genres = @movie.genres.order(:name)
    return unless current_user

    @favorite = current_user.favorites.find_by(movie_id: @movie.id)
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      # flash[:notice] = "Movie successfully updated!"
      # flash.alert = "Your alert msg"
      # redirect_to movie_path(@movie)
      # shortcut below
      redirect_to @movie, notice: 'Movie successfully updated!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: 'Movie successfully updated!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path, status: :see_other, alert: 'Movie sucesssfully removed'
  end

  private

  def set_movie
    @movie = Movie.find_by!(slug: params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :rating, :description, :total_gross, :released_on, :director, :duration,
                                  :image_file_name, genre_ids: [])
  end
end

# Dynamic way using ruby send
#
#   def index
#     @movies = Movie.send(movies_filter)
#   end
#
#   private
#   def movies_filter
#     if params[:filter].in? %w(upcoming recent hits flops)
#       params[:filter]
#     else
#       :released
#     end
#   end
#
# But do not do this below!
#
#   def index
#     if params[:filter]
#       @movies = Movie.send(params[:filter])
#     else
#       @movies = Movie.released
#     end
#   end

app/helpers/movies_helper.rb
module MoviesHelper
  def total_gross(movie)
    if movie.flop?
      'Flop!'
    else
      number_to_currency(movie.total_gross, precision: 0)
    end
  end

  def description(movie)
    truncate(movie.description, length: 150, seperator: ' ')
  end

  def release_year(movie)
    movie.released_on.year
  end

  def nav_link_to(text, url)
    if current_page?(url)
      link_to(text, url, class: "active")
    else
      link_to(text,url)
    end
  end
end

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form|%>
  <%= render "shared/errors", object: movie %>
  <%= form.label :title %>
  <%= form.text_field :title, autofocus: true %>
  <%= form.label :rating %>
  <%= form.select :rating, Movie::RATINGS, prompt: "Pick one" %>
  <%= form.label :description %>
  <%= form.text_area :description, rows: 10%>
  <%= form.label :total_gross %>
  <%= form.number_field :total_gross %>
  <%= form.label :released_on %>
  <%#= form.datetime_select :released_on, {discard_day: true, discard_hour:true}, {class: "date"} %>
  <%= form.date_field :released_on %>
  <%= form.label :director %>
  <%= form.text_field :director %>
  <%= form.label :duration %>
  <%= form.text_field :duration %>
  <%= form.label :image_file_name %>
  <%= form.text_field :image_file_name %>
  <div class="checkboxes">
    <%= form.collection_check_boxes(:genre_ids, Genre.order(:name), :id, :name)%>
  </div>
  <%= form.submit %>
<% end %>

app/views/movies/edit.html.erb
<h1>Edit <%= @movie.title %></h1>

<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
  <section class="movie">
    <div class="image">
      <%= image_tag movie.image_file_name%>
    </div>
    <div class="summary">
      <h2>
        <%= link_to(movie.title, movie_path(movie)) %>
      </h2>
      <h3>
        <%= release_year(movie)%>
      </h3>
      <h3>
        <%= total_gross(movie) %>
      </h3>
      <h3 class="stars">
        <%= render "shared/stars", percent: movie.average_stars_as_percent%>
      </h3>
      <p>
        <%= description(movie) %>
      </p>
    </div>
  </section>
<% end %>
<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Add New Movie", new_movie_path, class: "button" %>
  </section>
<% end %>

app/views/movies/new.html.erb
<h1>Add New Movie</h1>

<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<section class="movie-details">
  <div class="image">
    <%= image_tag @movie.image_file_name %>
    <% if current_user %>
      <div class="faves">
        <%= fave_or_unfave_button(@movie, @favorite) %>
        <div class="count">
          <%= @fans.size %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="details">
    <h1><%= @movie.title %></h1>
    <h2>
      <%= release_year(@movie) %> &bull; <%= @movie.rating %>
    </h2>
    <div class="reviews">
      <%= render "shared/stars", percent: @movie.average_stars_as_percent%>
      <%= link_to pluralize(@movie.reviews.count, "review"), movie_reviews_path(@movie)%>
    </div>
    <table>
      <tr>
        <th>Director:</th>
        <td><%= @movie.director %></td>
      </tr>
      <tr>
        <th>Duration:</th>
        <td><%= @movie.duration %></td>
      </tr>
      <tr>
        <th>Total Gross:</th>
        <td><%= total_gross(@movie) %></td>
      </tr>
      <tr>
        <th>Description:</th>
        <td><%= @movie.description %></td>
      </tr>
    </table>
    <div class="review">
      <%= render "reviews/new" %>
    </div>
  </div>
  <aside>
    <% if @fans.present? %>
      <h4>Fans</h4>
      <ul>
        <% @fans.each do |user| %>
          <li>
            <%= link_to user.name, user %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <% if @genres.present? %>
      <h4>Genre</h4>
      <ul>
        <% @genres.each do |genre| %>
          <li>
            <%= link_to genre.name, genre_path(genre) %>
          <% end %>
        </li>
      </ul>
    <% end %>
  </aside>
</section>
<% if current_user_admin? %>
  <section class="admin">
    <%= link_to("Edit", edit_movie_path(@movie), class: "button") %>
    <%= link_to "Delete", @movie, class: "button", data: { turbo_method: :delete, turbo_confirm: "Really?" } %>
  </section>
<% end %>